// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SistemaGestionOdontologica.Api.Data;

#nullable disable

namespace SistemaGestionOdontologica.Api.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SistemaGestionOdontologica.Api.Entities.ArchivoClinico", b =>
                {
                    b.Property<long>("IdArchivo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id_archivo");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("IdArchivo"));

                    b.Property<DateTime>("FechaSubida")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("fecha_subida")
                        .HasDefaultValueSql("SYSDATETIME()");

                    b.Property<int>("IdHistorial")
                        .HasColumnType("int")
                        .HasColumnName("id_historial");

                    b.Property<string>("NombreArchivo")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("nombre_archivo");

                    b.Property<string>("NombreOriginal")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("nombre_original");

                    b.Property<string>("Ruta")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("ruta");

                    b.Property<long>("TamanoBytes")
                        .HasColumnType("bigint")
                        .HasColumnName("tamano_bytes");

                    b.Property<string>("TipoMime")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("tipo_mime");

                    b.HasKey("IdArchivo");

                    b.HasIndex("IdHistorial");

                    b.ToTable("archivos_clinicos", (string)null);
                });

            modelBuilder.Entity("SistemaGestionOdontologica.Api.Entities.Bitacora", b =>
                {
                    b.Property<long>("IdBitacora")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id_bitacora");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("IdBitacora"));

                    b.Property<string>("Accion")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("accion");

                    b.Property<string>("Detalles")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("detalles");

                    b.Property<DateTime>("Fecha")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("fecha")
                        .HasDefaultValueSql("SYSDATETIME()");

                    b.Property<int>("IdUsuario")
                        .HasColumnType("int")
                        .HasColumnName("id_usuario");

                    b.HasKey("IdBitacora");

                    b.HasIndex("IdUsuario", "Fecha");

                    b.ToTable("bitacora", (string)null);
                });

            modelBuilder.Entity("SistemaGestionOdontologica.Api.Entities.HistorialClinico", b =>
                {
                    b.Property<int>("IdHistorial")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_historial");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdHistorial"));

                    b.Property<string>("Diagnostico")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("diagnostico");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("datetime2")
                        .HasColumnName("fecha");

                    b.Property<int>("IdOdontologo")
                        .HasColumnType("int")
                        .HasColumnName("id_odontologo");

                    b.Property<int>("IdPaciente")
                        .HasColumnType("int")
                        .HasColumnName("id_paciente");

                    b.Property<string>("MotivoConsulta")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("motivo_consulta");

                    b.Property<string>("Observaciones")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("observaciones");

                    b.HasKey("IdHistorial");

                    b.HasIndex("IdOdontologo");

                    b.HasIndex("IdPaciente");

                    b.ToTable("historial_clinico", (string)null);
                });

            modelBuilder.Entity("SistemaGestionOdontologica.Api.Entities.HistorialTratamiento", b =>
                {
                    b.Property<int>("IdHistorialTratamiento")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_historial_tratamiento");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdHistorialTratamiento"));

                    b.Property<int>("Cantidad")
                        .HasColumnType("int")
                        .HasColumnName("cantidad");

                    b.Property<int>("IdHistorial")
                        .HasColumnType("int")
                        .HasColumnName("id_historial");

                    b.Property<int>("IdTratamiento")
                        .HasColumnType("int")
                        .HasColumnName("id_tratamiento");

                    b.Property<decimal>("PrecioUnitario")
                        .HasColumnType("decimal(12,2)")
                        .HasColumnName("precio_unitario");

                    b.HasKey("IdHistorialTratamiento");

                    b.HasIndex("IdHistorial");

                    b.HasIndex("IdTratamiento");

                    b.ToTable("historial_tratamientos", null, t =>
                        {
                            t.HasCheckConstraint("CK_historial_tratamientos_cantidad", "[cantidad] > 0");

                            t.HasCheckConstraint("CK_historial_tratamientos_precio", "[precio_unitario] >= 0");
                        });
                });

            modelBuilder.Entity("SistemaGestionOdontologica.Api.Entities.Odontologo", b =>
                {
                    b.Property<int>("IdOdontologo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_odontologo");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdOdontologo"));

                    b.Property<bool>("Activo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true)
                        .HasColumnName("activo");

                    b.Property<string>("Apellido")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("apellido");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("email");

                    b.Property<string>("Especialidad")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("especialidad");

                    b.Property<string>("Matricula")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasColumnName("matricula");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("nombre");

                    b.Property<string>("Telefono")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("telefono");

                    b.HasKey("IdOdontologo");

                    b.HasIndex("Matricula")
                        .IsUnique();

                    b.ToTable("odontologos", (string)null);
                });

            modelBuilder.Entity("SistemaGestionOdontologica.Api.Entities.Paciente", b =>
                {
                    b.Property<int>("IdPaciente")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_paciente");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdPaciente"));

                    b.Property<bool>("Activo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true)
                        .HasColumnName("activo");

                    b.Property<string>("Apellido")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("apellido");

                    b.Property<string>("Direccion")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)")
                        .HasColumnName("direccion");

                    b.Property<string>("Dni")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)")
                        .HasColumnName("dni");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("email");

                    b.Property<DateTime>("FechaNacimiento")
                        .HasColumnType("date")
                        .HasColumnName("fecha_nacimiento");

                    b.Property<DateTime>("FechaRegistro")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("fecha_registro")
                        .HasDefaultValueSql("SYSDATETIME()");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("nombre");

                    b.Property<string>("Telefono")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("telefono");

                    b.HasKey("IdPaciente");

                    b.HasIndex("Dni")
                        .IsUnique();

                    b.ToTable("pacientes", (string)null);
                });

            modelBuilder.Entity("SistemaGestionOdontologica.Api.Entities.Pago", b =>
                {
                    b.Property<int>("IdPago")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_pago");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdPago"));

                    b.Property<DateTime>("FechaPago")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("fecha_pago")
                        .HasDefaultValueSql("SYSDATETIME()");

                    b.Property<int>("IdPaciente")
                        .HasColumnType("int")
                        .HasColumnName("id_paciente");

                    b.Property<string>("MetodoPago")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("metodo_pago");

                    b.Property<decimal>("Monto")
                        .HasColumnType("decimal(12,2)")
                        .HasColumnName("monto");

                    b.Property<string>("Observaciones")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("observaciones");

                    b.HasKey("IdPago");

                    b.HasIndex("IdPaciente");

                    b.ToTable("pagos", null, t =>
                        {
                            t.HasCheckConstraint("CK_pagos_metodo", "[metodo_pago] IN ('efectivo', 'tarjeta', 'transferencia')");

                            t.HasCheckConstraint("CK_pagos_monto", "[monto] > 0");
                        });
                });

            modelBuilder.Entity("SistemaGestionOdontologica.Api.Entities.RecordatorioTurno", b =>
                {
                    b.Property<long>("IdRecordatorio")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id_recordatorio");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("IdRecordatorio"));

                    b.Property<bool>("Enviado")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false)
                        .HasColumnName("enviado");

                    b.Property<string>("Error")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("error");

                    b.Property<DateTime?>("FechaEnvio")
                        .HasColumnType("datetime2")
                        .HasColumnName("fecha_envio");

                    b.Property<DateTime>("FechaProgramada")
                        .HasColumnType("datetime2")
                        .HasColumnName("fecha_programada");

                    b.Property<int>("IdTurno")
                        .HasColumnType("int")
                        .HasColumnName("id_turno");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("tipo");

                    b.HasKey("IdRecordatorio");

                    b.HasIndex("IdTurno");

                    b.HasIndex("Enviado", "FechaProgramada");

                    b.ToTable("recordatorios_turno", null, t =>
                        {
                            t.HasCheckConstraint("CK_recordatorios_tipo", "[tipo] IN ('email','whatsapp', 'sms')");
                        });
                });

            modelBuilder.Entity("SistemaGestionOdontologica.Api.Entities.Tratamiento", b =>
                {
                    b.Property<int>("IdTratamiento")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_tratamiento");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdTratamiento"));

                    b.Property<bool>("Activo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true)
                        .HasColumnName("activo");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("descripcion");

                    b.Property<DateTime>("FechaCreacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("fecha_creacion")
                        .HasDefaultValueSql("SYSDATETIME()");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("nombre");

                    b.Property<decimal>("Precio")
                        .HasColumnType("decimal(12,2)")
                        .HasColumnName("precio");

                    b.HasKey("IdTratamiento");

                    b.ToTable("tratamientos", null, t =>
                        {
                            t.HasCheckConstraint("CK_tratamientos_precio", "[precio] >= 0");
                        });
                });

            modelBuilder.Entity("SistemaGestionOdontologica.Api.Entities.Turno", b =>
                {
                    b.Property<int>("IdTurno")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_turno");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdTurno"));

                    b.Property<string>("Estado")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasDefaultValue("pendiente")
                        .HasColumnName("estado");

                    b.Property<DateTime>("FechaCreacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("fecha_creacion")
                        .HasDefaultValueSql("SYSDATETIME()");

                    b.Property<DateTime>("FechaHoraFin")
                        .HasColumnType("datetime2")
                        .HasColumnName("fecha_hora_fin");

                    b.Property<DateTime>("FechaHoraInicio")
                        .HasColumnType("datetime2")
                        .HasColumnName("fecha_hora_inicio");

                    b.Property<int>("IdOdontologo")
                        .HasColumnType("int")
                        .HasColumnName("id_odontologo");

                    b.Property<int>("IdPaciente")
                        .HasColumnType("int")
                        .HasColumnName("id_paciente");

                    b.Property<string>("Observaciones")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("observaciones");

                    b.HasKey("IdTurno");

                    b.HasIndex("IdPaciente");

                    b.HasIndex("IdOdontologo", "FechaHoraInicio");

                    b.ToTable("turnos", null, t =>
                        {
                            t.HasCheckConstraint("CK_turnos_estado", "[estado] IN ('pendiente', 'confirmado', 'cancelado', 'realizado')");

                            t.HasCheckConstraint("CK_turnos_fechas", "[fecha_hora_fin] > [fecha_hora_inicio]");
                        });
                });

            modelBuilder.Entity("SistemaGestionOdontologica.Api.Entities.Usuario", b =>
                {
                    b.Property<int>("IdUsuario")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_usuario");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdUsuario"));

                    b.Property<bool>("Activo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true)
                        .HasColumnName("activo");

                    b.Property<DateTime>("FechaCreacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("fecha_creacion")
                        .HasDefaultValueSql("SYSDATETIME()");

                    b.Property<int?>("IdOdontologo")
                        .HasColumnType("int")
                        .HasColumnName("id_odontologo");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("password_hash");

                    b.Property<string>("Rol")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("rol");

                    b.Property<DateTime?>("UltimoAcceso")
                        .HasColumnType("datetime2")
                        .HasColumnName("ultimo_acceso");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("username");

                    b.HasKey("IdUsuario");

                    b.HasIndex("IdOdontologo");

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("usuarios", null, t =>
                        {
                            t.HasCheckConstraint("CK_usuarios_rol", "[rol] IN ('admin', 'odontologo', 'recepcionista')");
                        });
                });

            modelBuilder.Entity("SistemaGestionOdontologica.Api.Entities.ArchivoClinico", b =>
                {
                    b.HasOne("SistemaGestionOdontologica.Api.Entities.HistorialClinico", "Historial")
                        .WithMany("Archivos")
                        .HasForeignKey("IdHistorial")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Historial");
                });

            modelBuilder.Entity("SistemaGestionOdontologica.Api.Entities.Bitacora", b =>
                {
                    b.HasOne("SistemaGestionOdontologica.Api.Entities.Usuario", "Usuario")
                        .WithMany("Bitacoras")
                        .HasForeignKey("IdUsuario")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("SistemaGestionOdontologica.Api.Entities.HistorialClinico", b =>
                {
                    b.HasOne("SistemaGestionOdontologica.Api.Entities.Odontologo", "Odontologo")
                        .WithMany("HistorialesClinicos")
                        .HasForeignKey("IdOdontologo")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SistemaGestionOdontologica.Api.Entities.Paciente", "Paciente")
                        .WithMany("HistorialesClinicos")
                        .HasForeignKey("IdPaciente")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Odontologo");

                    b.Navigation("Paciente");
                });

            modelBuilder.Entity("SistemaGestionOdontologica.Api.Entities.HistorialTratamiento", b =>
                {
                    b.HasOne("SistemaGestionOdontologica.Api.Entities.HistorialClinico", "Historial")
                        .WithMany("HistorialTratamientos")
                        .HasForeignKey("IdHistorial")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SistemaGestionOdontologica.Api.Entities.Tratamiento", "Tratamiento")
                        .WithMany("HistorialTratamientos")
                        .HasForeignKey("IdTratamiento")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Historial");

                    b.Navigation("Tratamiento");
                });

            modelBuilder.Entity("SistemaGestionOdontologica.Api.Entities.Pago", b =>
                {
                    b.HasOne("SistemaGestionOdontologica.Api.Entities.Paciente", "Paciente")
                        .WithMany("Pagos")
                        .HasForeignKey("IdPaciente")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Paciente");
                });

            modelBuilder.Entity("SistemaGestionOdontologica.Api.Entities.RecordatorioTurno", b =>
                {
                    b.HasOne("SistemaGestionOdontologica.Api.Entities.Turno", "Turno")
                        .WithMany("Recordatorios")
                        .HasForeignKey("IdTurno")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Turno");
                });

            modelBuilder.Entity("SistemaGestionOdontologica.Api.Entities.Turno", b =>
                {
                    b.HasOne("SistemaGestionOdontologica.Api.Entities.Odontologo", "Odontologo")
                        .WithMany("Turnos")
                        .HasForeignKey("IdOdontologo")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SistemaGestionOdontologica.Api.Entities.Paciente", "Paciente")
                        .WithMany("Turnos")
                        .HasForeignKey("IdPaciente")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Odontologo");

                    b.Navigation("Paciente");
                });

            modelBuilder.Entity("SistemaGestionOdontologica.Api.Entities.Usuario", b =>
                {
                    b.HasOne("SistemaGestionOdontologica.Api.Entities.Odontologo", "Odontologo")
                        .WithMany("Usuarios")
                        .HasForeignKey("IdOdontologo")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Odontologo");
                });

            modelBuilder.Entity("SistemaGestionOdontologica.Api.Entities.HistorialClinico", b =>
                {
                    b.Navigation("Archivos");

                    b.Navigation("HistorialTratamientos");
                });

            modelBuilder.Entity("SistemaGestionOdontologica.Api.Entities.Odontologo", b =>
                {
                    b.Navigation("HistorialesClinicos");

                    b.Navigation("Turnos");

                    b.Navigation("Usuarios");
                });

            modelBuilder.Entity("SistemaGestionOdontologica.Api.Entities.Paciente", b =>
                {
                    b.Navigation("HistorialesClinicos");

                    b.Navigation("Pagos");

                    b.Navigation("Turnos");
                });

            modelBuilder.Entity("SistemaGestionOdontologica.Api.Entities.Tratamiento", b =>
                {
                    b.Navigation("HistorialTratamientos");
                });

            modelBuilder.Entity("SistemaGestionOdontologica.Api.Entities.Turno", b =>
                {
                    b.Navigation("Recordatorios");
                });

            modelBuilder.Entity("SistemaGestionOdontologica.Api.Entities.Usuario", b =>
                {
                    b.Navigation("Bitacoras");
                });
#pragma warning restore 612, 618
        }
    }
}
